#!/bin/sh
echo upwn IPSW Dowload/Extraction Binaries are designed to be an open source project to the community, please feel free to add/contribute just please don't steal my work, if you want to use it. Just ask I don't bite 
echo CopyRight 2015 John Abercrombie @PWN24K
echo Source Code Here https://github.com/rhcp011235/upwn
echo much thanks to @rhcp011235
sleep 4s
echo This Version Currently Supports iOS 8.4 For The iPhone 5C 5,3 and 5,4 run upwn_help.sh for usage